### ISSUE TITLE
file opens up for like 0.2 second and crashes

### ISSUE THREAD

**Issue by IGOTTOKENLOG** [RandomGamingDev/EzCopenheimer#1]
title

how to replicate :
click on file with python
watch it crash

**Comment by RandomGamingDev** [comment]
Just a little recommendation, but you typically should use the command line as that way you can see what python version your using and the errors. The issue is most likely that you didn't install the libraries needed. Just go to the command line and use the `pip` to install the mcstatus, threading (this library is named thread6 in pip), and asyncio libraries by simply typing `pip install` and then the pip name and/or actual name if there isn't a `pip` specific name. If that doesn't work it's possible that you installed an older version of python although I'm going to assume that python is on your machine since it said that something popped up and "crashed" (or at least I'm assuming that something had to pop up for you to register a crash). Also, since you said that you clicked on the file, I'm going to say this just in case, but you have to open up the code in a text file editor (don't worry you don't have to edit the actual code) and just enter your IP ranges in the designated regions. Also, sorry if this reading gets tiring, but if you ever want to scan faster you'll quite likely want to use a JIT compiling implementation of Python called PyPy. If you ever do decide to use that simply install the libraries for it (online tutorials should do fine for this) and run it on the command line using the `pypy` command just as you would use the `python command`.

**Comment by bsl3** [comment]
sorry I never used python and have no knowledge on these things, I installed all the depednices things using the pip install, and the exact version, im on the latest verison of python, when I try to launch the .py file it crashes. I open the file with notepad, to edit it, like u said above, but im still confused on what to put in.

**Comment by RandomGamingDev** [comment]
> sorry I never used python and have no knowledge on these things, I installed all the depednices things using the pip install, and the exact version, im on the latest verison of python, when I try to launch the .py file it crashes. I open the file with notepad, to edit it, like u said above, but im still confused on what to put in.

Would you be able to send the error?
