### ISSUE TITLE
add an exclude list

### ISSUE THREAD

**Issue by ghost** [RandomGamingDev/EzCopenheimer#5]
there are some ips that "doesent really like" you scanning them and can get mad and you can get in legal trouble if you scan them, therefore i'd recomend adding an exclude list like the one from [masscan](https://github.com/robertdavidgraham/masscan/blob/master/data/exclude.conf)

**Comment by ghost** [comment]
if you want a lager list, you can use the one from [matscan](https://github.com/mat-1/masscan/blob/master/data/exclude.conf)

**Comment by RandomGamingDev** [comment]
> there are some ips that "doesent really like" you scanning them and can get mad and you can get in legal trouble if you scan them, therefore i'd recomend adding an exclude list like the one from [masscan](https://github.com/robertdavidgraham/masscan/blob/master/data/exclude.conf)

The official statement on [masscan](https://github.com/robertdavidgraham/masscan)'s README is:
```
Scanning the entire Internet is bad. For one thing, parts of the Internet react badly to being scanned. For another thing, some sites track scans and add you to a ban list, which will get you firewalled from useful parts of the Internet.
```
1. This statement doesn't mention legality, and for good reason. While there have been *very rare* cases where users of scanners being used as a basis to sue (e.g. [Scott Moulton and Network Installation Computer Services, Inc. v. VC3](http://www.internetlibrary.com/cases/lib_case37.cfm)) these cases more often than not fail to hold up to court scrutiny even when a corporation does decide that it's worth it to sue. The majority of these already quite rare lawsuits were due to the scanning being security oriented or causing damage, which just *barely manage* to *possibly* qualify under anti-cyber-damage laws (e.g. [18 U.S. Code § 1030 - Fraud and related activity in connection with computers](https://www.law.cornell.edu/uscode/text/18/1030)), with many of the court cases, at least in the US, being resolved on the side of the scanner! Let me remind you, EzCopenheimer does neither, only serving as an educational tool about the **dangers** of port scanning based server discovery for Minecraft servers. Not only that, but you have to consider the fact that all that's happening when you scan an IP is a single ping on a single non-sensitive port out of the **millions** or **billions** on a whole variety of ports that the organizations that even *slightly* have a chance of suing you deal with on a **daily** basis making it unreasonable to believe that they'd prosecute you for something so inconsequential in an expensive lawsuit they are likely to lose! It's safe to say that port scanning, although technically gray is closer to white than black.
2. This main concern with masscan is when scanning the whole internet, which EzCopenheimer, an educational tool absolutely isn't designed for in the first place. Not only would the added complexity of ip exclusion detract from its simplistic education-oriented design, but it wouldn't provide significant value, especially considering how unlikely it is for someone utilizing EzCopenheimer for learning about scanners to scan say, an intelligence agency's ip on a sensitive port.

Your fear mongering statement especially when taken alongside your spamming of EzCopenheimer with irrelevant issues as well as your self-promotion of your own repository have painted your spam as nothing more as an attempt at self-advertisement, which I would advise you to refrain from.

> if you want a lager list, you can use [mine](https://github.com/JacobDevWasTaken/Really-bad-copenheimer/blob/main/src/discover/port_scanner/exclude.txt)

Also, if we're going to talk about legality, **your repository's** current usage of [masscan](https://github.com/robertdavidgraham/masscan/tree/master)'s [exclude.confg](https://github.com/robertdavidgraham/masscan/blob/master/data/exclude.conf) **is against the law**. [masscan is under the AGPL-3.0 License](https://github.com/robertdavidgraham/masscan/tree/master?tab=AGPL-3.0-1-ov-file#readme) which differs from the copyleft [GPL-3.0 License](https://www.gnu.org/licenses/gpl-3.0.en.html) through its  "additional right that if the program is expressly designed to accept user requests and send responses over a network, the user is entitled to receive the source code of the version being used," (FSF, [The fundamentals of the AGPLv3](https://www.fsf.org/bulletin/2021/fall/the-fundamentals-of-the-agplv3)) with the rule that "For license compatibility reasons, written into section 13 of both the GPLv3 and the AGPLv3 is the explicit permission to link or combine any covered work under the other license. Paraphrased from the GPLv3 section 13; you have permission to link or combine any covered work with a work licensed **under the AGPLv3** into a single combined work," (FSF, [The fundamentals of the AGPLv3](https://www.fsf.org/bulletin/2021/fall/the-fundamentals-of-the-agplv3)). Your repository is currently under the GPL-3 license, not the AGPL-3 license, explicitly breaking the law. I have submitted a PR for both repositories correcting your legal mistake and would advise you to merge it promptly.

**Comment by ghost** [comment]
> Your fear mongering statement especially when taken alongside your spamming of EzCopenheimer with irrelevant issues as well as your self-promotion of your own repository have painted your spam as nothing more as an attempt at self-advertisement, which I would advise you to refrain from.

sorry for that, i did not mean to promote my repository in any way, i simply wanted to prevent pepole from getting in legal trouble for testing your scanner. 

PS: its **not** my list, i managed to find the original soruce, its from a fork of masscan, [matscan](https://github.com/mat-1/masscan/blob/master/data/exclude.conf)

**Comment by ghost** [comment]
> Your fear mongering statement especially when taken alongside your spamming of EzCopenheimer with irrelevant issues as well as your self-promotion of your own repository have painted your spam as nothing more as an attempt at self-advertisement, which I would advise you to refrain from.

I've updated my comment with the orginal source. Also, even though that your repo is only to show how scanners work, rather then being as efficent as possible, i'd recomend adding a notice to the readme telling pepole to **not** scan the whole(ipv4) internet

**Comment by ghost** [comment]
feel free to close this issue, or leave it open for others to see

edit: forgot this was closed

**Comment by ghost** [comment]
I've also merged your pull requests, thanks for pointing out(and fixing) the legal issue.

**Comment by RandomGamingDev** [comment]
> > Your fear mongering statement especially when taken alongside your spamming of EzCopenheimer with irrelevant issues as well as your self-promotion of your own repository have painted your spam as nothing more as an attempt at self-advertisement, which I would advise you to refrain from.
> 
> sorry for that, i did not mean to promote my repository in any way, i simply wanted to prevent pepole from getting in legal trouble for testing your scanner.
> 
> PS: its **not** my list, i managed to find the original soruce, its from a fork of masscan, [matscan](https://github.com/mat-1/masscan/blob/master/data/exclude.conf)

The issue is when you make it sound like more of a danger than it actually is like your statement that you "simply wanted to prevent pepole from getting in legal trouble for testing your scanner," despite the risk being like a terrible lottery: something that's barely if at all worth considering. It's good that you found the "original source" (your version was still modified and different), but that doesn't change the fact that you ignored the purpose of EzCopenheimer and spammed it with irrelevant issues, which I'd advise you to store in one issue if you truly found it to be a concern.

> > Your fear mongering statement especially when taken alongside your spamming of EzCopenheimer with irrelevant issues as well as your self-promotion of your own repository have painted your spam as nothing more as an attempt at self-advertisement, which I would advise you to refrain from.
> 
> I've updated my comment with the orginal source. Also, even though that your repo is only to show how scanners work, rather then being as efficent as possible, i'd recomend adding a notice to the readme telling pepole to **not** scan the whole(ipv4) internet

This tool isn't designed to scan the whole IPv4 internet and anyone trying to make it do so is wasting their time using a repository made as an educational demonstration instead of a solution like masscan. As such, I believe that adding the warning isn't necessary.
